name: Update Scholar Metrics

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC
  workflow_dispatch:      # Manual trigger

jobs:
  update-scholar-metrics:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scholarly pyyaml

      # Step 4: Fetch Google Scholar metrics
      - name: Fetch Google Scholar metrics
        run: |
          python fetch_scholar_metrics.py

      # Step 5: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 6: Commit and push updates
      - name: Commit and push updates
        run: |
          git add _data/scholar_metrics.yml
          git commit -m "Auto-update Google Scholar metrics [skip ci]" || echo "No changes to commit"
          git push --force-with-lease origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
